export const gameState = {
    countdownInterval: null,
    matchRunning: false,
    startCountdown: 0,
    matchElapsed: 0,
    endCooldown: 0,
    autoPhaseEnded: false,
    autoWinner: 'red',
    autoScoreRed: 0,
    autoScoreBlue: 0,
    hubRedActive: true,
    hubBlueActive: true,
    currentPhaseIdx: -1,
    sameTeamMode: false,
    p2Enabled: true,
    p1Input: 'keyboard',
    p2Input: 'keyboard2',
    p1StartIdx: 0,
    p2StartIdx: 0,
    p1UnstickUsed: false,
    p2UnstickUsed: false,
    p1FreezeUntil: 0,
    p2FreezeUntil: 0,
    gamepads: [null, null],
    p1GamepadIndex: 0,
    p2GamepadIndex: 1,
    scoreRed: 0,
    scoreBlue: 0,
    keys: {}
};